### ISSUE TITLE
Loss of footnotes with `aspectratio=169`

### ISSUE THREAD

**Issue by HanwGeek** [basaldella/beamerthemeuniud#1]
Hi, thanks for the excellent beamer template first.
However, when I set `aspectratio=169`, the pdf lose all footnote output such as page number, author. What should I do to fix this problem?
![image](https://user-images.githubusercontent.com/25524928/121116367-fe06ef80-c848-11eb-8b92-42e9b3bfdf6c.png)

**Comment by basaldella** [comment]
Hello! Did you mange to fix this issue?

**Comment by HanwGeek** [comment]
Hi, thanks for your reply! 
I noticed that the footnotes were defined with absolute positions but they would be out of page view in `169` mode.
I have fixed this issue by setting the footnote position dynamically with `\paperheight`.

**Comment by basaldella** [comment]
Oh, good to know! If you submit a PR I can integrate the fix in the repo.

**Comment by HanwGeek** [comment]
I have already open a PR. Please check it, thanks!

**Comment by basaldella** [comment]
Merged it into the main branch. Thank you very much for your contribution!
